openapi: 3.0.3
info:
  title: Spring Openapi Prototype
  description: Spring Openapi Prototype
  version: 1.0-SNAPSHOT
servers:
  - url: https://localhost:8080/api/v1
  - url: https://testenvironment.org/api/v1
  - url: https://prodenvironment.org/api/v1
tags:
  - name: users
    description: Users API Prototype
paths:
  /users:
    $ref: ./paths/v1/user.yaml
    